name: Push_Pentitugua

on:
  workflow_dispatch:     # 手动触发
  schedule:
    - cron: '30 9 * * *' # 北京时间17点30分

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install corpwechatbot beautifulsoup4

    - name: Push Pentitugua
      env: 
        WECOM_CORP_ID    : ${{secrets.WECOM_CORP_ID}}
        WECOM_CORP_SECRET: ${{secrets.WECOM_CORP_SECRET}}
        WECOM_AGENT_ID   : ${{secrets.WECOM_AGENT_ID}}
      run: python pentitugua.py